### ISSUE TITLE
Uploaders in a cat cannot find a category

### ISSUE THREAD

**Issue by Aktron** [Pleclown/Commons-Tools#5]
Hi! For a category (for example this one: https://commons.wikimedia.org/wiki/Category:Mediagrant:Wikiexpedice_Orlick%C3%A9_hory) I cant get a result. The Uploader in a cat tool says that the category does not exist. I've already mentioned this in December on Meta talk: https://meta.wikimedia.org/wiki/User_talk:Pleclown#The_tool_Uploaders_in_a_cat_appeears_to_be_unable_to_load_categories but got no reply.

**Comment by VojtechDostal** [comment]
@Aktron @urbanecm proposed a fix for this bug (above) but in the meantime you can use Martin's fork: https://urbanecm-test-1.toolforge.org/ptools/uploadersincat.php
